[[redirects]]
  from = "/yahoo-chart/*"
  to = "https://query1.finance.yahoo.com/v8/finance/chart/:splat"
  status = 200
  force = true
  [redirects.headers]
    User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    Referer = "https://finance.yahoo.com"

[[redirects]]
  from = "/investidor10/*"
  to = "https://investidor10.com.br/:splat"
  status = 200
  force = true
  [redirects.headers]
    User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    Referer = "https://investidor10.com.br"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
